version: '3.0'

services:
  nestjs:
    container_name: backend
    build:
      dockerfile: Dockerfile
      context: .
    env_file:
      - ./app/.env
    volumes:
      - ./app:/app
      - /app/node_modules
    ports:
      - "4000:4000"
    command: npm run start:dev
    depends_on:
      - postgres
    restart: always
  postgres:
    container_name: database
    image: postgres:15.2
    env_file:
      - ./app/.development.env
    environment:
      PG_DATA: /var/lib/postgresql/data
    ports:
      - "15432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: always

volumes:
  pgdata: